spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    hikari:
      username: root
      password: bd1998
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # 指定 namespace
#        namespace: 9d32c5e1-b7ce-4c59-a193-ce803002a02b
        # 指定集群名称
        cluster-name: NJ
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          input:
            destination: add-bonus
            # 一定要设置
            group: binder-group



  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: user-center


server:
  port: 8081


logging:
  level:
    com.alibaba.nacos: error

jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600
