spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    hikari:
      username: root
      password: bd1998
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848


  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: content-center

server:
  port: 8010
