spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    hikari:
      username: root
      password: bd1998
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        cluster-name: BJ
        # namespace:
    sentinel:
      transport:
        # 指定 sentinel 控制台 地址
        dashboard: localhost:8080
        # 关闭对SpringMVC端点的控制
      filter:
        enabled: false



  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: content-center
  main:
    allow-bean-definition-overriding: true


server:
  port: 8010

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients: user-center

logging:
  level:
    com.stackingrule.contentcenter.feignclient.UserCenterFeignClient: debug
#feign:
#  client:
#    config:
#      # 想要调用的微服务名称
#      user-center:
#        loggerLevel: full
feign:
  httpclient:
    # 让 feign 使用 apache htpclient 做请求，而不是默认的urlconnection
    enabled: true
    # feign 的最大连接数
    max-connections: 200
    # # feign 单个路径的最大连接数
    max-connections-per-route: 50


# actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'

# sentinel 控制台 整合
resttemplate:
  sentinel:
    # 关闭 @SentinelRestTemplate注解
    enabled: true
