server:
  port: 8040

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhoat:8848
    gateway:
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
